version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: db
    ports:
        - "5432:5432"
    expose:
      - 5432
    networks:
        - trans-network
    env_file: ../.env
    volumes:
        - db-v:/var/lib/postgresql/data
    restart: unless-stopped
  django:
    container_name: django
    build:
      context: ./django
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8000:8000"
    expose:
      - 8000
    env_file: ../.env
    networks:
      - trans-network
    volumes:
      - django-v:/home/django/ft_transcendence
      - certificates-v:/certificates
    restart: unless-stopped
  grafana:
    container_name: grafana
    depends_on:
     - prometheus
    build:
      context: ./grafana
      dockerfile: Dockerfile
    ports:
        - "3000:3000"
    expose:
      - 3000
    networks:
        - trans-network
    env_file: ../.env
    volumes:
        - grafana-v:/var/lib/grafana
    restart: unless-stopped
  prometheus:
    container_name: prometheus
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    depends_on:
     - django
    user: root
    ports:
      - "9090:9090"
    expose:
      - 9090
    env_file: ../.env
    networks:
      - trans-network
    volumes:
      - prometheus-v:/prometheus
      - certificates-v:/certificates
    restart: unless-stopped

volumes:
  django-v:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${PWD}/srcs/django/ft_transcendence"
  db-v:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${PWD}/srcs/data/db"
  prometheus-v:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${PWD}/srcs/data/prometheus"
  grafana-v:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${PWD}/srcs/data/grafana"
  certificates-v:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${PWD}/srcs/certificates"

networks:
  trans-network:
    driver: bridge
