# Generated by Django 4.2.13 on 2024-05-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(default='Stormbringer: A tempestuous warrior harnessing the power of lightning, striking fear into foes.'),
        ),
    ]
