# Generated by Django 4.2.11 on 2024-05-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(default='Celestial Guardian: A celestial warrior harnessing divine energy, defending justice with heavenly might.'),
        ),
    ]
