# Generated by Django 4.2.13 on 2024-06-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(default='Raging Bull: A hulking brute armed with a massive warhammer, causing devastation with every swing.'),
        ),
    ]
