# Generated by Django 4.2.11 on 2024-04-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(default='Silent Reaper: A master of stealth armed with deadly daggers, leaving no trace behind.'),
        ),
    ]
