# Generated by Django 4.2.11 on 2024-04-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(default='Crimson Blade: A relentless warrior wielding a fiery sword, leaving enemies scorched in battle.'),
        ),
    ]
