# Generated by Django 4.2.11 on 2024-05-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(default='Raging Bull: A hulking brute armed with a massive warhammer, causing devastation with every swing.'),
        ),
    ]
