# Generated by Django 4.2.11 on 2024-04-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_profile_losses_profile_wins_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='wins',
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(default='Raging Bull: A hulking brute armed with a massive warhammer, causing devastation with every swing.'),
        ),
    ]
