# Generated by Django 4.2.11 on 2024-04-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_profile_losses_remove_profile_wins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(default='Phoenix Fury: A mystical warrior capable of summoning flames, rising from ashes to conquer.'),
        ),
    ]
