# Generated by Django 4.2.11 on 2024-04-30 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_userstatsproxy'),
        ('accounts', '0021_alter_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userstats',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.userstats'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(default='Crimson Blade: A relentless warrior wielding a fiery sword, leaving enemies scorched in battle.'),
        ),
    ]
