# Generated by Django 4.2.11 on 2024-04-30 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_userstats_goals_conceded_userstats_goals_scored_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatsProxy',
            fields=[
            ],
            options={
                'verbose_name': 'User Stats',
                'verbose_name_plural': 'User Stats',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('stats.userstats',),
        ),
    ]
