# Generated by Django 4.2.11 on 2024-04-30 19:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_userstatsproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='match_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None),
        ),
    ]
