# Generated by Django 4.2.11 on 2024-04-26 23:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_players', models.IntegerField(choices=[(4, '4'), (8, '8'), (16, '16')])),
                ('elimination_type', models.CharField(choices=[('single', 'Single Elimination'), ('double', 'Double Elimination')], max_length=20)),
                ('players', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
