# Generated by Django 4.2.11 on 2024-04-27 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
