# Generated by Django 4.2.11 on 2024-04-27 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0003_participant_tournament_created_at_tournamentmatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='round_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winning_matches', to='pong.participant'),
        ),
    ]
