# Generated by Django 4.2.11 on 2024-04-27 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pong', '0004_tournamentmatch_round_number_tournamentmatch_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='elimination_type',
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='participant1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant1_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='participant2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant2_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winning_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
