{
 "title": "a Django Prometheus",
 "description": "Django metrics dashboard using korfuri/django-prometheus Prometheus metrics exporter",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(django_db_new_connections_total, namespace)"
   },
   {
    "name": "app",
    "label": "app",
    "query": "label_values(django_db_new_connections_total{namespace=~\"$namespace\"}, app)"
   }
  ]
 },
 "panels": [
  {
   "title": "Alerts history",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "ALERTS", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP Responses by Status",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "transcendance_django_http_responses_total_by_status_view_method_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus: HTTP Request Total",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prometheus_http_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 13, "x": 11, "y": 18 },
   "targets": [
    {
     "expr": "transcendance_django_http_requests_latency_seconds_by_view_method_sum",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}